require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

AllCops:
  TargetRubyVersion: 2.5.3

Style/RedundantSelf:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/*'
